import { roomHash, roomNonce, publicRoomPath } from './roomCrypto';
import { validNickname } from './visitorIdentity';
export interface CafeAccount { kind:'account'; id:string; accountId:string; sessionId:string; nickname:string; displayName:string; avatar?:string }
export interface CafeAccountState { enabled:boolean; status:'idle'|'loading'|'ready'|'unavailable'; mode:'choose'|'guest'|'account'; account:CafeAccount|null; busy:boolean; error:string|null }
const object=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==='object'&&!Array.isArray(v);
const token=(v:unknown):v is string=>typeof v==='string'&&/^[A-Za-z0-9_-]{43}$/.test(v);
export function parseCafeAccount(v:unknown):CafeAccount {
 if(!object(v)||v.kind!=='account'||typeof v.id!=='string'||!/^[a-f0-9]{8}$/.test(v.id)||typeof v.accountId!=='string'||!/^[a-f0-9]{64}$/.test(v.accountId)||v.id!==v.accountId.slice(0,8)||!token(v.sessionId)||typeof v.nickname!=='string'||!validNickname(v.nickname)||v.displayName!==v.nickname+'#'+v.id)throw Error('INVALID_ACCOUNT_STATE');
 let avatar:string|undefined;if(typeof v.avatar==='string'){const u=new URL(v.avatar);if(u.protocol!=='https:'||u.username||u.password||u.href.length>2048)throw Error('INVALID_ACCOUNT_STATE');avatar=u.href;}
 return{kind:'account',id:v.id,accountId:v.accountId,sessionId:v.sessionId,nickname:v.nickname,displayName:String(v.displayName),...(avatar?{avatar}:{})};
}
export async function accountRequest(path:'session'|'start'|'logout'|'logout-all'|'attest',value?:Record<string,unknown>,signal?:AbortSignal):Promise<Record<string,unknown>> {
 const abort=new AbortController(),stop=()=>abort.abort();if(signal?.aborted)throw Error('ACCOUNT_REQUEST_CANCELLED');signal?.addEventListener('abort',stop,{once:true});const timer=setTimeout(stop,7000);
 try{const response=await fetch('/api/identity/'+path,{method:value===undefined?'GET':'POST',credentials:'same-origin',cache:'no-store',redirect:'error',signal:abort.signal,headers:{Accept:'application/json',...(value?{'Content-Type':'application/json','X-Cafe-Identity':'1'}:{})},...(value?{body:JSON.stringify(value)}:{})});const text=await response.text();if(text.length>16384)throw Error('INVALID_ACCOUNT_STATE');let result:unknown;try{result=JSON.parse(text);}catch{throw Error('ACCOUNT_SERVICE_UNAVAILABLE');}if(!response.ok)throw Error(response.status===401?'ACCOUNT_LOGIN_REQUIRED':response.status===429?'ACCOUNT_RATE_LIMITED':'ACCOUNT_SERVICE_UNAVAILABLE');if(!object(result))throw Error('INVALID_ACCOUNT_STATE');return result;}catch(e){const code=e instanceof Error?e.message:'';throw Error(['INVALID_ACCOUNT_STATE','ACCOUNT_LOGIN_REQUIRED','ACCOUNT_RATE_LIMITED','ACCOUNT_SERVICE_UNAVAILABLE'].includes(code)?code:signal?.aborted?'ACCOUNT_REQUEST_CANCELLED':'ACCOUNT_SERVICE_UNAVAILABLE');}finally{clearTimeout(timer);signal?.removeEventListener('abort',stop);}
}
export function safeAccountDestination(value:unknown):string {
 if(typeof value!=='string'||value.length>8192)throw Error('INVALID_ACCOUNT_STATE');const u=new URL(value);
 const test=window.location.protocol==='http:'&&['localhost','127.0.0.1','[::1]'].includes(window.location.hostname)&&u.protocol==='http:'&&['localhost','127.0.0.1','[::1]'].includes(u.hostname);
 if(u.username||u.password||u.hash||(!test&&u.origin!=='https://www.cafecode.work')||!['/oidc/auth','/sso/signout'].includes(u.pathname))throw Error('INVALID_ACCOUNT_STATE');return u.href;
}
export async function requestAccountAttestation(account:CafeAccount,room:string,connectionId:string,nonce:string,publicKey:string,signal?:AbortSignal){
 const r=await accountRequest('attest',{roomHash:await roomHash(room),connectionId,nonce,publicKey},signal),identity=parseCafeAccount(r.identity);
 if(identity.accountId!==account.accountId||identity.sessionId!==account.sessionId)throw Error('ACCOUNT_IDENTITY_CHANGED');
 if(typeof r.assertion!=='string'||r.assertion.length>6144||r.assertion.split('.').length!==3||!Number.isSafeInteger(r.expiresAt)||Number(r.expiresAt)<=Date.now()||Number(r.expiresAt)>Date.now()+65000)throw Error('INVALID_ACCOUNT_STATE');
 return{identity,assertion:r.assertion,expiresAt:Number(r.expiresAt),userId:'account-'+(await roomHash(identity.accountId+':'+identity.sessionId+':'+room+':'+publicKey)).slice(0,24)};
}
export class CafeAccountController {
 #state:CafeAccountState={enabled:false,status:'idle',mode:'choose',account:null,busy:false,error:null};#listeners=new Set<()=>void>();#cancel=new AbortController();#disposed=false;#checking:Promise<void>|null=null;#timer:ReturnType<typeof setInterval>|undefined;#generation=0;
 readonly #resume=()=>{if(!this.#disposed&&this.#state.enabled&&document.visibilityState!=='hidden')void this.refresh();};
 readonly #pageshow=()=>{if(this.#state.busy)this.#update({busy:false});this.#resume();};
 readonly #storage=(e:StorageEvent)=>{if(e.key==='cafe-space.account-event')this.#resume();};
 getSnapshot=()=>this.#state;subscribe=(fn:()=>void)=>{this.#listeners.add(fn);return()=>{this.#listeners.delete(fn);};};
 #update(change:Partial<CafeAccountState>){if(this.#disposed)return;this.#state={...this.#state,...change};for(const fn of this.#listeners)fn();}
 enable(value:boolean){if(this.#state.enabled===value)return;this.#update({enabled:value});if(!value)return;let preferred:string|null=null;try{preferred=localStorage.getItem('cafe-space.identity-choice');}catch{}if(preferred==='guest'||preferred==='account')this.#update({mode:preferred});this.#update({status:'loading'});void this.refresh();this.#timer=setInterval(this.#resume,15000);window.addEventListener('storage',this.#storage);window.addEventListener('online',this.#resume);window.addEventListener('pageshow',this.#pageshow);document.addEventListener('visibilitychange',this.#resume);}
 async refresh():Promise<void>{if(!this.#state.enabled||this.#disposed)return;if(this.#checking)return this.#checking;const generation=this.#generation;
 const task=(async()=>{try{const data=await accountRequest('session',undefined,this.#cancel.signal);if(this.#disposed||generation!==this.#generation)return;if(data.enabled!==true||typeof data.authenticated!=='boolean')throw Error('INVALID_ACCOUNT_STATE');const account=data.authenticated?parseCafeAccount(data.identity):null;this.#update({status:'ready',account,error:!account&&this.#state.mode==='account'?'ACCOUNT_LOGIN_REQUIRED':null});}catch(e){if(!this.#disposed&&generation===this.#generation)this.#update({status:'unavailable',error:e instanceof Error?e.message:'ACCOUNT_SERVICE_UNAVAILABLE'});}finally{this.#checking=null;}})();this.#checking=task;return task;}
 choose(mode:'choose'|'guest'|'account'){if(mode==='account'&&!this.#state.account)throw Error('ACCOUNT_LOGIN_REQUIRED');this.#update({mode,error:null});try{if(mode==='choose')localStorage.removeItem('cafe-space.identity-choice');else localStorage.setItem('cafe-space.identity-choice',mode);}catch{}}
 async start(returnPath:string){if(this.#state.busy||!this.#state.enabled)return;const destination=publicRoomPath(returnPath)?returnPath:'/';const transaction=roomNonce();try{sessionStorage.setItem('cafe-space.login.'+transaction,JSON.stringify({path:destination,created:Date.now()}));sessionStorage.setItem('cafe-space.login.latest',transaction);}catch{throw Error('ACCOUNT_LOGIN_STORAGE_UNAVAILABLE');}this.#update({busy:true,error:null});try{const r=await accountRequest('start',{transaction},this.#cancel.signal);window.location.assign(safeAccountDestination(r.url));}catch(e){this.#update({busy:false,error:e instanceof Error?e.message:'ACCOUNT_SERVICE_UNAVAILABLE'});throw e;}}
 async complete(transaction:string|null,error:string|null):Promise<string>{let id=transaction;try{if(!id)id=sessionStorage.getItem('cafe-space.login.latest');}catch{}if(!token(id))throw Error('ACCOUNT_LOGIN_TRANSACTION_EXPIRED');let record:unknown;try{record=JSON.parse(sessionStorage.getItem('cafe-space.login.'+id)??'null');sessionStorage.removeItem('cafe-space.login.'+id);sessionStorage.removeItem('cafe-space.login.latest');}catch{throw Error('ACCOUNT_LOGIN_TRANSACTION_EXPIRED');}if(!object(record)||typeof record.created!=='number'||Date.now()-record.created>600000||record.created>Date.now()+5000||typeof record.path!=='string'||record.path!=='/'&&!publicRoomPath(record.path))throw Error('ACCOUNT_LOGIN_TRANSACTION_EXPIRED');if(error){this.#update({mode:'choose',busy:false,error:error==='cancelled'?'ACCOUNT_LOGIN_CANCELLED':'ACCOUNT_LOGIN_FAILED'});return record.path;}await this.refresh();if(!this.#state.account)throw Error('ACCOUNT_LOGIN_REQUIRED');this.choose('account');this.#update({busy:false});try{localStorage.setItem('cafe-space.account-event',String(Date.now()));}catch{}return record.path;}
 async logout(){if(this.#state.busy)return;this.#generation++;this.#update({busy:true});try{await accountRequest('logout',{},this.#cancel.signal);this.#update({account:null,mode:'choose',error:null,status:'ready'});try{localStorage.removeItem('cafe-space.identity-choice');localStorage.setItem('cafe-space.account-event',String(Date.now()));}catch{}}catch(e){this.#update({error:e instanceof Error?e.message:'ACCOUNT_SERVICE_UNAVAILABLE'});throw e;}finally{this.#update({busy:false});}}
 async logoutAll(returnPath:string){if(this.#state.busy)return;try{const transaction=roomNonce();sessionStorage.setItem('cafe-space.login.'+transaction,JSON.stringify({path:publicRoomPath(returnPath)?returnPath:'/',created:Date.now()}));sessionStorage.setItem('cafe-space.login.latest',transaction);}catch{}this.#update({busy:true});try{const r=await accountRequest('logout-all',{},this.#cancel.signal);window.location.assign(safeAccountDestination(r.url));}catch(e){this.#update({busy:false,error:e instanceof Error?e.message:'ACCOUNT_SERVICE_UNAVAILABLE'});throw e;}}
 dispose(){this.#disposed=true;this.#cancel.abort();clearInterval(this.#timer);window.removeEventListener('storage',this.#storage);window.removeEventListener('online',this.#resume);window.removeEventListener('pageshow',this.#pageshow);document.removeEventListener('visibilitychange',this.#resume);this.#listeners.clear();}
}
