import { afterEach, expect, it, vi } from 'vitest';
import { CafeAccountController, parseCafeAccount, requestAccountAttestation } from './cafeAccount';
const controllers:CafeAccountController[]=[];const account={kind:'account' as const,id:'a'.repeat(8),accountId:'a'.repeat(64),sessionId:'s'.repeat(43),nickname:'拿铁',displayName:'拿铁#'+'a'.repeat(8)};
const response=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json'}});
afterEach(()=>{controllers.splice(0).forEach(c=>c.dispose());vi.unstubAllGlobals();localStorage.clear();sessionStorage.clear();});
function controller(){const c=new CafeAccountController();controllers.push(c);return c;}
it('a signed-in main account never silently replaces the chosen guest identity',async()=>{localStorage.setItem('cafe-space.identity-choice','guest');vi.stubGlobal('fetch',vi.fn(async()=>response({enabled:true,authenticated:true,identity:account})));const c=controller();c.enable(true);await c.refresh();expect(c.getSnapshot().mode).toBe('guest');expect(c.getSnapshot().account?.displayName).toBe(account.displayName);c.choose('account');expect(c.getSnapshot().mode).toBe('account');});
it('first entry remains an explicit choice even when a Space account session exists',async()=>{vi.stubGlobal('fetch',vi.fn(async()=>response({enabled:true,authenticated:true,identity:account})));const c=controller();c.enable(true);await c.refresh();expect(c.getSnapshot().mode).toBe('choose');});
it('the OAuth return restores a browser-local room destination without storing a password',async()=>{vi.stubGlobal('fetch',vi.fn(async()=>response({enabled:true,authenticated:true,identity:account})));const c=controller();c.enable(true);const transaction='t'.repeat(43),path='/room/'+'B'+'A'.repeat(86);sessionStorage.setItem('cafe-space.login.'+transaction,JSON.stringify({path,created:Date.now()}));expect(await c.complete(transaction,null)).toBe(path);expect(c.getSnapshot().mode).toBe('account');expect(sessionStorage.getItem('cafe-space.login.'+transaction)).toBeNull();await expect(c.complete(transaction,null)).rejects.toThrow('ACCOUNT_LOGIN_TRANSACTION_EXPIRED');expect(localStorage.getItem('cafe-space.identity-choice')).toBe('account');});
it('cancelled login preserves the room but never authenticates as a guest automatically',async()=>{vi.stubGlobal('fetch',vi.fn(async()=>response({enabled:true,authenticated:false})));const c=controller();c.enable(true);const id='t'.repeat(43);sessionStorage.setItem('cafe-space.login.'+id,JSON.stringify({path:'/',created:Date.now()}));expect(await c.complete(id,'cancelled')).toBe('/');expect(c.getSnapshot().mode).toBe('choose');expect(c.getSnapshot().error).toBe('ACCOUNT_LOGIN_CANCELLED');});
it('forged profile labels and changed account sessions cannot be used for room assertions',async()=>{expect(()=>parseCafeAccount({...account,displayName:'administrator'})).toThrow();expect(()=>parseCafeAccount({...account,accountId:'b'.repeat(64)})).toThrow();vi.stubGlobal('fetch',vi.fn(async()=>response({identity:{...account,sessionId:'x'.repeat(43)},assertion:'a.b.c',expiresAt:Date.now()+60000})));await expect(requestAccountAttestation(account,'B'+'A'.repeat(86),'c'.repeat(43),'n'.repeat(43),'B'+'A'.repeat(86))).rejects.toThrow('ACCOUNT_IDENTITY_CHANGED');});
it('Space-only logout clears the account choice and never stores a primary access token',async()=>{const fetch=vi.fn(async(_url:unknown,init?:RequestInit)=>response(init?.method==='POST'?{ok:true}:{enabled:true,authenticated:true,identity:account}));vi.stubGlobal('fetch',fetch);const c=controller();c.enable(true);await c.refresh();c.choose('account');await c.logout();expect(c.getSnapshot().account).toBeNull();expect(c.getSnapshot().mode).toBe('choose');expect(fetch.mock.calls.some(([url])=>url==='/api/identity/logout')).toBe(true);expect([...Array(localStorage.length)].map((_,i)=>localStorage.key(i))).not.toContain('access_token');});
