import assert from 'node:assert/strict';
import { readFile, writeFile, mkdir, copyFile, realpath } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { randomBytes } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import { root, run, sha } from './build.mjs';
import { releaseFiles } from './release.mjs';
import { baseEnv } from './native-support.mjs';
if(process.platform!=='win32'||!process.argv.includes('--allow-manual'))throw Error('Explicit manual installation/start authorization required');
const directory=join(root,'.refactor/manual-trial');
const piRoot='C:/Users/dp/AppData/Local/pnpm/global/5/.pnpm/@earendil-works+pi-coding-a_92f687cfe951df750bec0864ffeea219/node_modules/@earendil-works/pi-coding-agent';
const archive=join(root,'.refactor/release/pack-30bbqJ/cafecodework-pi-cafe-space-0.1.0.tgz');
const pack=JSON.parse(await readFile(join(dirname(archive),'pack-report.json'),'utf8'));
assert.equal(sha(await readFile(archive)),'32ee907b902174495ed3e1ea9307a8f339cd8df79ede3e7f23e50eeccc94bfd2');assert.deepEqual(pack.files,releaseFiles(pack.platforms));
const tar=join(process.env.SystemRoot,'System32/tar.exe');assert.deepEqual(run(tar,['-tzf',archive]).trim().split(/\r?\n/).sort(),pack.files.map(n=>'package/'+n).sort());assert.ok(run(tar,['-tvzf',archive]).trim().split(/\r?\n/).every(n=>n.startsWith('-')));
await mkdir(directory); // Refuse an existing install, never overwrite unknown files.
await writeFile(join(directory,'.trial-owned'),randomBytes(16).toString('hex'),{flag:'wx'});
const ps=join(process.env.SystemRoot,'System32/WindowsPowerShell/v1.0/powershell.exe');
await writeFile(join(directory,'private-acl.ps1'),`$ErrorActionPreference='Stop'\n$acl=New-Object Security.AccessControl.DirectorySecurity\n$acl.SetAccessRuleProtection($true,$false)\nforeach($sid in @([Security.Principal.WindowsIdentity]::GetCurrent().User.Value,'S-1-5-18')){$identity=New-Object Security.Principal.SecurityIdentifier($sid);$rule=New-Object Security.AccessControl.FileSystemAccessRule($identity,'FullControl','ContainerInherit,ObjectInherit','None','Allow');$acl.AddAccessRule($rule)}\nSet-Acl -LiteralPath $PSScriptRoot -AclObject $acl\n`);
run(ps,['-NoProfile','-ExecutionPolicy','Bypass','-File',join(directory,'private-acl.ps1')],{env:baseEnv(),timeout:30000});
for(const folder of ['project','agent','sessions','home','temp','chrome-profile'])await mkdir(join(directory,folder));
await writeFile(join(directory,'package.json'),JSON.stringify({name:'pi-cafe-space-manual-trial',private:true,dependencies:{'@earendil-works/pi-coding-agent':'file:'+piRoot,'@cafecodework/pi-cafe-space':'file:'+archive}}));
await writeFile(join(directory,'npmrc'),'');await writeFile(join(directory,'global-npmrc'),'');
run(process.execPath,[join(root,'.refactor/toolchains/npm11/package/bin/npm-cli.js'),'install','--prefix',directory,'--workspaces=false','--omit=dev','--ignore-scripts','--package-lock=false','--no-audit','--no-fund','--offline','--logs-dir',join(directory,'npm-logs'),'--userconfig',join(directory,'npmrc'),'--globalconfig',join(directory,'global-npmrc')],{cwd:directory,env:baseEnv(),timeout:120000});
const pkg=join(directory,'node_modules/@cafecodework/pi-cafe-space');const require=createRequire(join(pkg,'package.json'));assert.ok((await realpath(require.resolve('ws'))).toLowerCase().startsWith(directory.toLowerCase()));assert.equal(JSON.parse(await readFile(require.resolve('ws/package.json'),'utf8')).version,'8.21.3');
for(const mode of ['check','test'])assert.match(run(process.execPath,[join(pkg,'scripts/source-verify.mjs'),mode],{cwd:directory,env:{...baseEnv(),PATH:''},timeout:30000}),/Prebuilt artifact verification only/);
const config={format:'pi-cafe-space-manual-trial-v1',root:directory,node:await realpath(process.execPath),piCli:join(piRoot,'dist/cli.js'),package:pkg,models:'C:/Users/dp/.pi/agent/models.json',chrome:await realpath(join(process.env.LOCALAPPDATA,'Google/Chrome SxS/Application/chrome.exe')),room:'manual-trial',peer:'manual-trial-pi',hostToken:randomBytes(24).toString('hex'),clientToken:randomBytes(24).toString('hex')};
await writeFile(join(directory,'credentials.json'),JSON.stringify(config,null,2),{flag:'wx'});
await writeFile(join(directory,'agent/settings.json'),JSON.stringify({enableInstallTelemetry:false,compaction:{enabled:false},retry:{enabled:false},defaultProjectTrust:'never'}));
for(const name of ['manual-runtime.mjs','manual-verify.mjs','native-support.mjs','native-process.ps1'])await copyFile(fileURLToPath(new URL('./'+name,import.meta.url)),join(directory,name));
for(const name of ['provider.mjs','pi-console.ps1','launch-console.ps1'])await copyFile(fileURLToPath(new URL('./manual-trial/'+name,import.meta.url)),join(directory,name));
for(const mode of ['Start','Stop'])await writeFile(join(directory,mode+'.cmd'),`@echo off\r\n"${config.node}" "%~dp0manual-runtime.mjs" ${mode.toLowerCase()}\r\nif errorlevel 1 pause\r\n`);
await writeFile(join(directory,'README.txt'),`Pi Cafe Space 本机试用\r\n\r\n网页：http://127.0.0.1:37983/ （只监听本机）\r\n启动：双击 Start.cmd；已运行时不要重复启动。\r\n停止：先结束正在执行的任务，再双击 Stop.cmd。只停止本试用记录的进程，保留安装和会话。\r\n项目：${join(directory,'project')}\r\n会话：${join(directory,'sessions')}\r\n\r\n已实际安装 Go/React 候选包，原生 Pi 0.85.1 在独立控制台运行。网页已自动登录；本地 Pi 窗口保留给权限确认和本地 UI。\r\n只在 Pi 内存中读取你现有 cafe/gpt-6-astra 配置，不复制 provider 密钥，不修改全局设置。没有假模型、测试工具或预设回复；使用 Pi 原生 provider 和工具。\r\n安装器不会发送 prompt。之后由你在网页或 Pi 中提交真实请求，费用按你的服务端配置产生；此前自动验收的 2x1024 限额不套在你手动操作上。\r\n网页若需要重新登录，房间为 manual-trial；客户端令牌在本目录 credentials.json 的 clientToken。它不是模型密钥。\r\nStop.cmd 将结束本试用的 Pi/Chrome/Relay；用户自行启动的工具子进程不作批量清理。\r\n未替换旧服务/生产入口；这里只供你手动验收。\r\n`);
// Parse each new console script before opening a window.
await writeFile(join(directory,'parse.ps1'),`$ErrorActionPreference='Stop'\nforeach($name in @('pi-console.ps1','launch-console.ps1')){$t=$null;$e=$null;$null=[Management.Automation.Language.Parser]::ParseFile((Join-Path $PSScriptRoot $name),[ref]$t,[ref]$e);if($e.Count){throw 'PowerShell parse failed'}}\n`);
run(ps,['-NoProfile','-ExecutionPolicy','Bypass','-File',join(directory,'parse.ps1')],{env:baseEnv(),timeout:30000});
console.log('Installed verified candidate: '+directory);
console.log(run(process.execPath,[join(directory,'manual-runtime.mjs'),'start'],{cwd:directory,env:baseEnv(),timeout:180000}));
