import { mkdir, readFile, writeFile, copyFile, chmod } from 'node:fs/promises';
import { randomBytes, createHash } from 'node:crypto';
import { isIP } from 'node:net';
import { dirname, isAbsolute, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { parseArgs } from 'node:util';
import { plainOrigin } from './install-client.mjs';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'../..');
const TURN_IMAGE='coturn/coturn:4.18.0-r0@sha256:bbefd3e1fdfdc0d58770fe01b581fd8b00d9f3a5580d00acb77cf719a6bc78e3';
const secret=()=>randomBytes(32).toString('base64url');
export function serverOptions(v) {
 if(!v.out||!isAbsolute(v.out)||/[\u0000-\u001f\u007f]/.test(v.out))throw Error('--out must be a new absolute directory');
 const origin=plainOrigin(v.origin??'');const u=new URL(origin);
 if(u.port||!/^[a-z0-9](?:[a-z0-9.-]*[a-z0-9])?$/i.test(u.hostname)||!u.hostname.includes('.'))throw Error('Use a DNS hostname on HTTPS port 443');
 if(isIP(v['public-ip'])!==4)throw Error('--public-ip must be the server public IPv4 address');
 const b=v['public-ip'].split('.').map(Number);
 if(b[0]===0||b[0]===10||b[0]===127||b[0]>=224||b[0]===169&&b[1]===254||b[0]===172&&b[1]>=16&&b[1]<=31||b[0]===192&&b[1]===168||b[0]===100&&b[1]>=64&&b[1]<=127)throw Error('A routable public IPv4 address is required');
 const arch=v.arch??'amd64';if(!['amd64','arm64'].includes(arch))throw Error('Linux amd64 or arm64 required');
 const proxy=v.proxy??'existing';if(!['existing','caddy'].includes(proxy))throw Error('--proxy must be existing or caddy');
 return{out:resolve(v.out),origin,hostname:u.hostname,ip:v['public-ip'],arch,proxy};
}
export async function configure(v) {
 const o=serverOptions(v);const{relayBinary}=await import(pathToFileURL(join(root,'scripts/relay-path.mjs')));const binary=await relayBinary(root,'linux-'+o.arch);
 const turnSecret=secret();const cfg={mode:'cloud',publicOrigin:o.origin,roomAccess:true,enableWebRTC:true,iceServers:[{urls:['stun:'+o.ip+':3478']}],turn:{urls:['turn:'+o.ip+':3478?transport=udp','turn:'+o.ip+':3478?transport=tcp'],sharedSecret:turnSecret,ttlSeconds:3600}};
 await mkdir(o.out,{mode:0o700});for(const d of ['cloud-image','turn','turn/image','caddy'])await mkdir(join(o.out,d),{mode:0o700});
 const put=(name,text,mode=0o600)=>writeFile(join(o.out,name),text,{flag:'wx',mode});
 await copyFile(binary,join(o.out,'cloud-image/pi-cafe-relay'),1);await chmod(join(o.out,'cloud-image/pi-cafe-relay'),0o555);
 await put('cloud-image/Dockerfile','FROM scratch\nCOPY --chmod=0555 pi-cafe-relay /pi-cafe-relay\nUSER 65532:65532\nEXPOSE 37892\nENTRYPOINT ["/pi-cafe-relay"]\n');
 await put('cloud.json',JSON.stringify(cfg,null,2)+'\n');await put('cloud-runtime.env','PI_COLLAB_HOST_TOKEN='+secret()+'\nPI_COLLAB_CLIENT_TOKEN='+secret()+'\n');
 await put('turn/image/Dockerfile',`FROM ${TURN_IMAGE}\nUSER root\nRUN cp --no-preserve=all /usr/bin/turnserver /usr/bin/turnserver.unprivileged && cmp /usr/bin/turnserver /usr/bin/turnserver.unprivileged && chmod 0555 /usr/bin/turnserver.unprivileged && mv /usr/bin/turnserver.unprivileged /usr/bin/turnserver\nUSER 65534:65534\n`);
 await put('turn/turnserver.conf',`listening-port=3478\nlistening-ip=${o.ip}\nrelay-ip=${o.ip}\nexternal-ip=${o.ip}\nrealm=${o.hostname}\nserver-name=${o.hostname}\nfingerprint\nuse-auth-secret\nstatic-auth-secret=${turnSecret}\nstale-nonce=600\nmax-allocate-timeout=30\nmax-allocate-lifetime=3600\nmin-port=49160\nmax-port=49259\nuser-quota=12\ntotal-quota=96\nmax-bps=1048576\nbps-capacity=8388608\nrelay-threads=2\nno-tls\nno-tcp-relay\nno-multicast-peers\nno-software-attribute\nunauthorized-ratelimit\nunauthorized-ratelimit-rps=10\nlog-file=stdout\nsimple-log\npidfile=/tmp/turnserver.pid\ndenied-peer-ip=0.0.0.0-0.255.255.255\ndenied-peer-ip=10.0.0.0-10.255.255.255\ndenied-peer-ip=100.64.0.0-100.127.255.255\ndenied-peer-ip=127.0.0.0-127.255.255.255\ndenied-peer-ip=169.254.0.0-169.254.255.255\ndenied-peer-ip=172.16.0.0-172.31.255.255\ndenied-peer-ip=192.168.0.0-192.168.255.255\ndenied-peer-ip=198.18.0.0-198.19.255.255\ndenied-peer-ip=224.0.0.0-255.255.255.255\ndenied-peer-ip=::1\ndenied-peer-ip=fc00::-fdff:ffff:ffff:ffff:ffff:ffff:ffff:ffff\ndenied-peer-ip=fe80::-febf:ffff:ffff:ffff:ffff:ffff:ffff:ffff\n`);
 const caddy=`${o.hostname} {\n    reverse_proxy 127.0.0.1:37892\n}\n`;await put('caddy/Caddyfile',caddy);await put('caddy-site.snippet',caddy);
 let compose=`name: cafe-room\nservices:\n  cloud:\n    build: ./cloud-image\n    image: cafe-room-cloud:local\n    platform: linux/${o.arch}\n    user: "65532:65532"\n    read_only: true\n    cap_drop: [ALL]\n    security_opt: ["no-new-privileges:true"]\n    restart: unless-stopped\n    pids_limit: 64\n    mem_limit: 512m\n    stop_grace_period: 20s\n    env_file: [./cloud-runtime.env]\n    environment:\n      PI_COLLAB_HOST: "0.0.0.0"\n      PI_COLLAB_PORT: "37892"\n      PI_COLLAB_ALLOWED_ORIGINS: "${o.origin}"\n      PI_CAFE_REMOTE_CONFIG: /run/cafe/cloud.json\n    ports: ["127.0.0.1:37892:37892"]\n    volumes:\n      - type: bind\n        source: ./cloud.json\n        target: /run/cafe/cloud.json\n        read_only: true\n        bind:\n          create_host_path: false\n    logging:\n      options: {max-size: "10m", max-file: "3"}\n  turn:\n    build: ./turn/image\n    image: cafe-room-turn:4.18.0-unprivileged\n    platform: linux/${o.arch}\n    entrypoint: [turnserver]\n    command: ["-c", "/run/cafe/turnserver.conf"]\n    network_mode: host\n    user: "65534:65534"\n    read_only: true\n    cap_drop: [ALL]\n    security_opt: ["no-new-privileges:true"]\n    restart: unless-stopped\n    pids_limit: 64\n    mem_limit: 256m\n    stop_grace_period: 15s\n    tmpfs:\n      - /tmp:rw,noexec,nosuid,size=16m,mode=1777\n      - /var/lib/coturn:rw,noexec,nosuid,size=4m,uid=65534,gid=65534,mode=0700\n    volumes:\n      - type: bind\n        source: ./turn/turnserver.conf\n        target: /run/cafe/turnserver.conf\n        read_only: true\n        bind:\n          create_host_path: false\n    logging:\n      options: {max-size: "10m", max-file: "3"}\n`;
 if(o.proxy==='caddy')compose+=`  caddy:\n    image: caddy:2.11.6\n    network_mode: host\n    restart: unless-stopped\n    volumes:\n      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro\n      - caddy_data:/data\n      - caddy_config:/config\n    logging:\n      options: {max-size: "10m", max-file: "3"}\nvolumes:\n  caddy_data:\n  caddy_config:\n`;
 await put('compose.yaml',compose);
 const start=`#!/bin/sh\n# Explicitly run on the selected Linux server after reviewing ports, DNS and firewall.\nset -eu\ncd "$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"\n[ "$(id -u)" -eq 0 ] || { echo 'Run as the authorized server administrator; no automatic sudo.' >&2; exit 2; }\nfor file in cloud.json cloud-runtime.env turn/turnserver.conf compose.yaml; do [ -f "$file" ] && [ ! -L "$file" ] || { echo 'Invalid deployment file' >&2; exit 2; }; done\nsha256sum -c MANIFEST.sha256\nif [ -n "$(docker ps -aq --filter label=com.docker.compose.project=cafe-room)" ]; then echo 'A cafe-room stack already exists; use a reviewed upgrade, not this new-install script.' >&2; exit 3; fi\nchmod 700 . turn\nchown 65532:65532 cloud.json\nchmod 400 cloud.json\nchown 65534:65534 turn/turnserver.conf\nchmod 400 turn/turnserver.conf\nchmod 600 cloud-runtime.env\ndocker compose config --quiet\ndocker compose up -d --build\necho 'Containers started. Verify HTTPS /api/config roomAccess=true, then connect an office gateway. Container start is not P2P verification.'\n`;
 await put('start-server.sh',start,0o700);
 await put('SERVER-README.md',`# Café Space self-host deployment\n\nOrigin: ${o.origin}\nArchitecture: Linux ${o.arch}\nProxy choice: ${o.proxy}\n\nThis generator has NOT changed DNS, firewall, services or any existing Caddy configuration. Keep this directory private: it contains a TURN shared secret and independent internal runtime keys. It contains no room password or owner identity.\n\n1. Copy the directory to a NEW server location. Confirm Docker Compose is installed; inspect existing containers, listeners and firewall. This template assumes the public IP ${o.ip} is configured on the host itself, not behind NAT.\n2. ${o.proxy==='existing'?'Merge caddy-site.snippet into the existing HOST-network or host Caddy only after backing up and checking active config. A bridged proxy must instead share a reviewed Docker network with cloud; its own localhost is not this server. Validate before reload. Do not replace other sites.':'This stack starts a new Caddy container on the host network. Do not run it if 80/443 are already occupied. Set DNS for '+o.hostname+' before startup.'}\n3. Permit inbound 80/443 TCP for HTTPS and TURN 3478 TCP/UDP plus 49160–49259 UDP, keeping SSH and the original firewall rules. The script does not alter the firewall. Do not send TURN through an ordinary Cloudflare HTTP proxy.\n4. Run sh ./start-server.sh as the authorized administrator. The manifest is an integrity check, not a publisher signature. Store backups outside the document root.\n5. Check docker compose ps, HTTPS healthz and api/config; test a newly registered office room with two devices and verify the actual ICE candidate pair. TURN/TLS 5349 is not configured by this template.\n\nOffice computers use ${o.origin} as --server. No per-office account needs to be added here.\n\nUpgrade: generate a NEW release directory, preserve existing server runtime/TURN secrets where desired, inspect hashes, and recreate ONLY this stack's cloud/turn services. Never use docker system prune or overwrite unrelated Caddy files. Rollback uses the old config/image and retained room identities on office computers.\n`);
 const files=['cloud-image/Dockerfile','cloud-image/pi-cafe-relay','cloud.json','cloud-runtime.env','turn/image/Dockerfile','turn/turnserver.conf','compose.yaml','caddy/Caddyfile','caddy-site.snippet','start-server.sh','SERVER-README.md'];let manifest='';for(const f of files)manifest+=createHash('sha256').update(await readFile(join(o.out,f))).digest('hex')+'  '+f+'\n';await put('MANIFEST.sha256',manifest);
 return{created:true,directory:o.out,origin:o.origin,architecture:o.arch,proxy:o.proxy,roomMode:true,turnConfigured:true,serverMutated:false,next:'Review SERVER-README.md; upload to a new server directory and explicitly run start-server.sh after DNS/port/firewall checks.'};
}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url)){
 try{const{values}=parseArgs({strict:true,options:{out:{type:'string'},origin:{type:'string'},'public-ip':{type:'string'},arch:{type:'string'},proxy:{type:'string'},help:{type:'boolean'}}});if(values.help)console.log('configure-server --out <new directory> --origin https://your.domain --public-ip <server IPv4> [--arch amd64|arm64] [--proxy existing|caddy]\nCreates a secret-bearing Docker stack; does NOT connect to a server or change services. Existing proxy is the safe default.');else console.log(JSON.stringify(await configure(values),null,2));}
 catch(e){console.error('Café Space server setup: '+e.message);process.exitCode=1;}
}
