import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import { CommandGateway } from './CommandGateway';
import { CollabStore } from '../../state/CollabStore';
import type { RelayEvent, ConnectionState } from './RelayClient';
import type { ClientCommandMessage, WireMessage, JsonValue } from '../../../../src/protocol/index';
const baseSnapshot = { protocolVersion: 1 as const, streamId: 's', sessionId: 'session', sessionName: null, cwd: 'C:/project', activeLeafId: null, model: null, thinkingLevel: 'off' as const, phase: 'running' as const, hasPendingMessages: false, messages: [], tools: [], historyTruncated: false, lastEventSeq: 0 };
function setup() {
    const state: ConnectionState = { generation: 1, roomId: 'main', status: 'authenticated' };
    const listeners = new Set<(e: RelayEvent) => void>();
    const sent: ClientCommandMessage[] = [];
    const store = new CollabStore(vi.fn());
    store.ingest({ kind: 'state', generation: 1, state });
    const emit = (message: WireMessage) => { const event: RelayEvent = { kind: 'message', generation: 1, message }; store.ingest(event); for (const fn of listeners)
        fn(event); };
    emit({ type: 'host_status', connected: true, streamId: 's', sessionId: 'session', hostId: 'h', hosts: [{ hostId: 'h', streamId: 's', sessionId: 'session', cwd: 'C:/project', sessionName: null, connected: true, ready: true }] });
    emit({ type: 'snapshot', hostId: 'h', snapshot: baseSnapshot });
    const client = { getState: () => state, subscribe: (fn: (e: RelayEvent) => void) => { listeners.add(fn); return () => { listeners.delete(fn); }; }, sendCommand: (message: ClientCommandMessage) => { sent.push(message); } };
    const gateway = new CommandGateway(client, store);
    const scope = store.scope()!;
    const result = (index: number, status: 'applied' | 'dispatched' | 'rejected' = 'applied', data?: JsonValue, code: string | null = null) => emit({ type: 'command_result', hostId: 'h', requestId: sent[index]!.requestId, status, code, message: null, ...data === undefined ? {} : { data } });
    return { store, client, gateway, scope, sent, emit, result };
}
beforeEach(() => vi.useFakeTimers());
afterEach(() => vi.useRealTimers());
it('gates input capabilities, validates inventory, isolates completion reads and never replays command writes', async () => {
    const x = setup();
    expect((await x.gateway.execute({ name: 'list_commands' }, x.scope)).code).toBe('INPUT_ASSIST_UNAVAILABLE');
    expect((await x.gateway.execute({ name: 'prompt', content: 'read', files: ['a'] }, x.scope)).code).toBe('INPUT_ASSIST_UNAVAILABLE');
    x.emit({ type: 'snapshot', hostId: 'h', snapshot: { ...baseSnapshot, inputAssist: true } });
    expect((await x.gateway.execute({ name: 'run_command', command: '/review' }, x.scope)).code).toBe('SESSION_BUSY');
    x.emit({ type: 'snapshot', hostId: 'h', snapshot: { ...baseSnapshot, inputAssist: true, phase: 'idle' } });
    const panel = x.gateway.execute({ name: 'list_dir', path: '.' }, x.scope);
    const completion = x.gateway.execute({ name: 'list_dir', path: 'src' }, x.scope, { transient: true });
    x.result(1, 'applied', { kind: 'directory', path: 'src', entries: [], truncated: false });
    expect((await completion).status).toBe('applied'); expect(x.store.getSnapshot().panels).toEqual({});
    x.result(0, 'applied', { kind: 'directory', path: '.', entries: [], truncated: false });
    expect((await panel).status).toBe('applied'); expect(x.store.getSnapshot().panels.directory).toMatchObject({ path: '.' });
    const invalid = x.gateway.execute({ name: 'list_commands' }, x.scope);
    x.result(2, 'applied', { kind: 'commands', commands: [{ name: '../bad', source: 'extension', description: '' }], truncated: false });
    expect((await invalid).code).toBe('RESULT_INVALID');
    const write = x.gateway.execute({ name: 'run_command', command: '/review' }, x.scope);
    expect((await x.gateway.execute({ name: 'run_command', command: '/review' }, x.scope)).code).toBe('SESSION_BUSY');
    x.result(3, 'rejected', undefined, 'HOST_NOT_READY'); expect((await write).code).toBe('HOST_NOT_READY');
    x.emit({ type: 'snapshot', hostId: 'h', snapshot: { ...baseSnapshot, inputAssist: true, phase: 'idle' } });
    expect(x.sent).toHaveLength(4);
    const pending = x.gateway.execute({ name: 'list_commands' }, x.scope); x.store.changeView();
    expect((await pending).code).toBe('VIEW_CHANGED'); expect(x.gateway.stats().count).toBe(0);
    x.gateway.dispose(); x.store.dispose();
});
it('gates session controls by capability and idle state, serializes duplicate actions and never retries a switch', async () => {
    const x = setup();
    expect((await x.gateway.execute({ name: 'new_session' }, x.scope)).code).toBe('SESSION_CONTROL_UNAVAILABLE');
    x.emit({ type: 'snapshot', hostId: 'h', snapshot: { ...baseSnapshot, sessionControl: true } });
    expect((await x.gateway.execute({ name: 'new_session' }, x.scope)).code).toBe('SESSION_BUSY');
    x.emit({ type: 'snapshot', hostId: 'h', snapshot: { ...baseSnapshot, sessionControl: true, phase: 'idle', hasPendingMessages: true } });
    expect((await x.gateway.execute({ name: 'new_session' }, x.scope)).code).toBe('SESSION_BUSY');
    x.emit({ type: 'snapshot', hostId: 'h', snapshot: { ...baseSnapshot, sessionControl: true, phase: 'idle' } });
    const first = x.gateway.execute({ name: 'resume_session', sessionId: 'saved/%2F:id' }, x.scope);
    expect(x.sent[0]).toMatchObject({ expectedSessionId: 'session', expectedCwd: 'C:/project', payload: { name: 'resume_session', sessionId: 'saved/%2F:id' } });
    expect((await x.gateway.execute({ name: 'new_session' }, x.scope)).code).toBe('SESSION_BUSY');
    x.result(0, 'rejected', undefined, 'SESSION_CANCELLED');
    expect((await first).code).toBe('SESSION_CANCELLED');
    const timed = x.gateway.execute({ name: 'new_session' }, x.scope);
    x.result(1, 'rejected', undefined, 'HOST_TIMEOUT');
    expect((await timed).status).toBe('unknown');
    expect(x.sent).toHaveLength(2);
    const accepted = x.gateway.execute({ name: 'new_session' }, x.scope);
    x.result(2, 'dispatched');
    expect((await accepted).status).toBe('dispatched');
    x.emit({ type: 'snapshot', hostId: 'h', snapshot: { ...baseSnapshot, streamId: 'new', sessionId: 'next', sessionControl: true, phase: 'idle' } });
    expect(x.store.scope()?.sessionId).toBe('next');
    expect(x.sent).toHaveLength(3);
    x.gateway.dispose(); x.store.dispose();
});
it('registers before sending, validates data binding and keeps running after dispatched', async () => {
    const x = setup();
    x.client.sendCommand = (m) => { x.sent.push(m); x.result(0, 'dispatched'); };
    const result = await x.gateway.execute({ name: 'abort' }, x.scope);
    expect(result.status).toBe('dispatched');
    expect(x.store.getSnapshot().hosts.get('h')!.snapshot!.phase).toBe('running');
    expect(x.gateway.stats().count).toBe(0);
    x.gateway.dispose();
    x.store.dispose();
});
it('does not settle REQUEST_PENDING or extend its original deadline', async () => {
    const x = setup();
    const p = x.gateway.execute({ name: 'abort' }, x.scope);
    x.result(0, 'dispatched', undefined, 'REQUEST_PENDING');
    expect(x.gateway.stats().count).toBe(1);
    vi.advanceTimersByTime(20000);
    expect((await p).code).toBe('RESULT_UNKNOWN');
    expect(x.sent).toHaveLength(1);
    x.gateway.dispose();
});
it('rejects wrong-kind results and old file selection cannot overwrite new file', async () => {
    const x = setup();
    const a = x.gateway.execute({ name: 'read_file', path: 'a' }, x.scope);
    const b = x.gateway.execute({ name: 'read_file', path: 'b' }, x.scope);
    x.result(1, 'applied', { kind: 'file', path: 'b', offset: 0, size: 1, bytesRead: 1, truncated: false, content: 'B' });
    expect((await b).status).toBe('applied');
    x.result(0, 'applied', { kind: 'file', path: 'a', offset: 0, size: 1, bytesRead: 1, truncated: false, content: 'A' });
    expect((await a).code).toBe('VIEW_CHANGED');
    expect(x.store.getSnapshot().panels.file).toMatchObject({ content: 'B' });
    const list = x.gateway.execute({ name: 'list_sessions' }, x.scope);
    x.result(2, 'applied', { kind: 'session', sessionId: 'history' });
    expect((await list).code).toBe('RESULT_INVALID');
    x.gateway.dispose();
});
it('fences context and view changes; local cancellation never sends abort', async () => {
    const x = setup();
    const controller = new AbortController();
    const p = x.gateway.execute({ name: 'prompt', content: 'hello' }, x.scope, { signal: controller.signal });
    controller.abort();
    expect((await p).code).toBe('RESULT_UNKNOWN');
    expect(x.sent).toHaveLength(1);
    const q = x.gateway.execute({ name: 'list_dir', path: '.' }, x.scope);
    x.store.changeView();
    expect((await q).code).toBe('VIEW_CHANGED');
    expect(x.gateway.stats()).toEqual({ count: 0, bytes: 0 });
    x.gateway.dispose();
});
it('allows offline history only and retries readonly not-ready once after authoritative snapshot', async () => {
    const x = setup();
    const pending = x.gateway.execute({ name: 'list_dir', path: '.' }, x.scope);
    x.result(0, 'rejected', undefined, 'HOST_NOT_READY');
    expect(x.sent).toHaveLength(1);
    x.emit({ type: 'snapshot', hostId: 'h', snapshot: baseSnapshot });
    expect(x.sent).toHaveLength(2);
    expect(x.sent[1]!.requestId).not.toBe(x.sent[0]!.requestId);
    x.result(1, 'rejected', undefined, 'HOST_NOT_READY');
    expect((await pending).code).toBe('HOST_NOT_READY');
    x.emit({ type: 'host_status', connected: false, hostId: 'h', streamId: 's', sessionId: 'session', hosts: [{ hostId: 'h', connected: false, ready: false, streamId: 's', sessionId: 'session', cwd: 'C:/project', sessionName: null }] });
    expect((await x.gateway.execute({ name: 'abort' }, x.scope)).code).toBe('HOST_OFFLINE');
    expect((await x.gateway.execute({ name: 'read_file', path: 'a' }, x.scope)).code).toBe('HOST_OFFLINE');
    const history = x.gateway.execute({ name: 'list_sessions' }, x.scope);
    x.result(2, 'applied', { kind: 'sessions', currentSessionId: 'session', sessions: [], historyTruncated: false });
    expect((await history).status).toBe('applied');
    x.gateway.dispose();
});
it('reserves pending capacity for abort and releases it on dispose', async () => {
    const x = setup();
    const pending = Array.from({ length: 31 }, () => x.gateway.execute({ name: 'prompt', content: 'hello' }, x.scope));
    expect((await x.gateway.execute({ name: 'prompt', content: 'overflow' }, x.scope)).code).toBe('COMMAND_QUEUE_FULL');
    pending.push(x.gateway.execute({ name: 'abort' }, x.scope));
    expect(x.gateway.stats().count).toBe(32);
    x.gateway.dispose();
    await Promise.all(pending);
    expect(x.gateway.stats()).toEqual({ count: 0, bytes: 0 });
    expect(vi.getTimerCount()).toBe(0);
});
it('reports uncertain host acknowledgements honestly and never replays writes', async () => {
    for (const code of ['HOST_TIMEOUT', 'HOST_REPLACED', 'HOST_OFFLINE', 'RESULT_TOO_LARGE']) {
        const x = setup();
        const p = x.gateway.execute({ name: 'prompt', content: 'hello' }, x.scope);
        x.result(0, 'rejected', undefined, code);
        expect((await p).status).toBe('unknown');
        expect(x.sent).toHaveLength(1);
        x.gateway.dispose();
    }
});
it('binds history IDs, context and byte quota, and rejects stale generation results', async () => {
    const x = setup();
    const p = x.gateway.execute({ name: 'list_sessions' }, x.scope);
    x.result(0, 'applied', { kind: 'sessions', currentSessionId: 'foreign', sessions: [] });
    expect((await p).code).toBe('RESULT_INVALID');
    const pending = x.gateway.execute({ name: 'read_file', path: 'a' }, x.scope);
    x.store.ingest({ kind: 'state', generation: 2, state: { status: 'connecting', generation: 2, roomId: 'main' } });
    expect((await pending).code).toBe('CONNECTION_CHANGED');
    x.result(1, 'applied', { kind: 'file', path: 'a', offset: 0, size: 1, bytesRead: 1, content: 'a', truncated: false });
    expect(x.store.getSnapshot().panels).toEqual({});
    expect(x.gateway.stats()).toEqual({ count: 0, bytes: 0 });
    x.gateway.dispose();
});
it('preserves original timeout through a readonly retry and releases its listener', async () => {
    const x = setup();
    const p = x.gateway.execute({ name: 'list_dir', path: '.' }, x.scope);
    vi.advanceTimersByTime(19000);
    x.result(0, 'rejected', undefined, 'HOST_NOT_READY');
    x.emit({ type: 'snapshot', hostId: 'h', snapshot: baseSnapshot });
    expect(x.sent).toHaveLength(2);
    vi.advanceTimersByTime(1000);
    expect((await p).code).toBe('TIMEOUT');
    expect(x.gateway.stats()).toEqual({ count: 0, bytes: 0 });
    x.gateway.dispose();
    expect(vi.getTimerCount()).toBe(0);
});
