import { afterEach, expect, it, vi } from 'vitest';
import { AppOwner } from './owner';
import { RelayClient, type SocketLike } from '../services/relay/RelayClient';
import { createRelayStorage } from '../services/relay/storage';
import ordered from '../../../protocol/fixtures/parts/ordered.json';
const owners:AppOwner[]=[];afterEach(()=>{owners.splice(0).forEach(o=>o.dispose());vi.restoreAllMocks();});
class Socket implements SocketLike{readyState=1;bufferedAmount=0;onopen:(()=>void)|null=null;onclose:(()=>void)|null=null;onerror:(()=>void)|null=null;onmessage:((e:{data:unknown})=>void)|null=null;send(){}close(){}emit(v:unknown){this.onmessage?.({data:JSON.stringify(v)});}}
async function setup(){
 const socket=new Socket();const owner=new AppOwner({client:new RelayClient({origin:'http://localhost',socketFactory:()=>socket}),storage:createRelayStorage(()=>{throw Error('isolated');}),http:{config:async()=>({protocolVersion:1,wsPath:'/ws',defaultRoom:'main'})}});owners.push(owner);await owner.initialize();owner.login('synthetic','main');socket.onopen?.();socket.emit({type:'welcome',protocolVersion:1,connectionId:'c',peerRole:'client',roomId:'main',hostConnected:true});
 const s=ordered.expectedFinal;const hosts=['a','b'].map(hostId=>({hostId,connected:true,ready:true,streamId:s.streamId,sessionId:s.sessionId,cwd:s.cwd,sessionName:hostId}));socket.emit({type:'host_status',hostId:'a',connected:true,streamId:s.streamId,sessionId:s.sessionId,hosts});for(const hostId of ['a','b'])socket.emit({type:'snapshot',hostId,snapshot:s});owner.selectHost('a');owner.remote.enable(true);const canWrite=vi.spyOn(owner.remote,'canWrite').mockReturnValue(false);let release!:()=>void;const acquire=vi.spyOn(owner.remote,'ensureControl').mockImplementation(()=>new Promise<void>(r=>{release=()=>{canWrite.mockReturnValue(true);r();};}));const execute=vi.spyOn(owner.gateway,'execute').mockResolvedValue({status:'applied',code:null,message:null});const scope=owner.store.scope();expect(scope).not.toBeNull();return{owner,scope:scope!,acquire,execute,release:()=>release()};
}
it('sends once only after acquisition and current-context checks',async()=>{const f=await setup();const task=f.owner.execute({name:'prompt',content:'one'},f.scope);expect(f.acquire).toHaveBeenCalledOnce();expect(f.execute).not.toHaveBeenCalled();f.release();expect((await task).status).toBe('applied');expect(f.execute).toHaveBeenCalledOnce();});
it.each(['switch','disconnect','cancel'])('does not dispatch after %s while awaiting control',async action=>{const f=await setup(),abort=new AbortController();const task=f.owner.execute({name:'prompt',content:'never send'},f.scope,{signal:abort.signal});if(action==='switch')f.owner.selectHost('b');else if(action==='disconnect')f.owner.client.stop();else abort.abort();f.release();expect((await task).status).toBe('rejected');expect(f.execute).not.toHaveBeenCalled();});
it('read-only requests do not acquire control',async()=>{const f=await setup();await f.owner.execute({name:'list_sessions'},f.scope);expect(f.acquire).not.toHaveBeenCalled();expect(f.execute).toHaveBeenCalledOnce();});
