import { describe, expect, it } from 'vitest';
import { ExecutionTracker } from './execution-tracker.js';
import { isExecutionState } from '../protocol/execution.js';
const setup=()=>{let sequence=0;return new ExecutionTracker(()=>`run-${++sequence}`);};
describe('native run observations',()=>{
 it('startup idle is not proof of any completed task',()=>{const s=setup();expect(s.snapshot()).toEqual({version:1,runId:null,activity:'idle',outcome:'none'});s.reset(false);expect(s.snapshot().activity).toBe('working');expect(s.snapshot().outcome).toBe('none');});
 it('settled cancellation wins over content and provisional success',()=>{const s=setup();s.begin();s.assistantEnded('stop');s.beforeSettle('completed');expect(s.snapshot().outcome).toBe('none');s.settled(true);expect(s.snapshot().outcome).toBe('aborted');const end=s.snapshot();s.settled(false);expect(s.snapshot()).toEqual(end);});
 it.each(['completed','error','aborted'] as const)('native boundary %s is final only after settled',outcome=>{const s=setup();s.begin();s.beforeSettle(outcome);expect(s.snapshot().outcome).toBe('none');s.settled(false);expect(s.snapshot().outcome).toBe(outcome);});
 it('retryable error and automatic continuation do not finish or split the run',()=>{const s=setup();s.begin();const id=s.snapshot().runId;s.assistantEnded('error');s.beforeSettle('error');expect(s.snapshot().outcome).toBe('none');s.begin();expect(s.snapshot().runId).toBe(id);s.assistantStarted();s.assistantEnded('stop');s.beforeSettle('completed');s.settled(false);expect(s.snapshot()).toMatchObject({runId:id,activity:'idle',outcome:'completed'});s.begin();expect(s.snapshot().runId).not.toBe(id);expect(s.snapshot().outcome).toBe('none');});
 it('missing native final evidence remains unknown, not inferred from idle',()=>{const s=setup();s.begin();s.settled(undefined);expect(s.snapshot().outcome).toBe('unknown');s.reset();s.settled(false);expect(s.snapshot().outcome).toBe('unknown');s.reset();s.begin();s.assistantEnded('toolUse');s.settled(false);expect(s.snapshot().outcome).toBe('unknown');});
 it('old settled payload can still retain a witnessed last assistant stop reason',()=>{const s=setup();s.begin();s.assistantEnded('error');s.settled(undefined);expect(s.snapshot().outcome).toBe('error');s.begin();s.assistantEnded('stop');s.settled(undefined);expect(s.snapshot().outcome).toBe('completed');});
 it('nested prompts retain their kinds and restore last settled result after independent UI',()=>{const s=setup();s.begin();s.beforeSettle('completed');s.settled(false);s.wait(true,'confirm',true);s.wait(true,'input',true);expect(s.snapshot()).toMatchObject({activity:'waiting',waitKind:'input',outcome:'none'});s.wait(false,'input',true);expect(s.snapshot().waitKind).toBe('confirm');s.wait(false,'confirm',true);expect(s.snapshot()).toMatchObject({activity:'idle',outcome:'completed'});});
 it('compaction belongs to activity, never manufactures a completed run',()=>{const s=setup();s.compactionStart('manual');expect(s.snapshot()).toMatchObject({activity:'compacting',reason:'manual',outcome:'none'});s.compactionEnd(true);expect(s.snapshot()).toMatchObject({activity:'idle',outcome:'none'});s.begin();const id=s.snapshot().runId;s.assistantEnded('error');s.compactionStart('overflow');s.compactionEnd(false);s.begin();expect(s.snapshot().runId).toBe(id);s.beforeSettle('completed');s.settled(false);expect(s.snapshot().outcome).toBe('completed');});
 it('scope reset, recovery, invalid kinds and large prompt depth stay bounded',()=>{const s=setup();s.begin();s.beforeSettle('error');s.reset();s.settled(false);expect(s.snapshot().outcome).toBe('unknown');s.begin();for(let i=0;i<200;i++)s.wait(true,'malicious-title-not-a-kind',false);expect(s.snapshot().waitKind).toBeUndefined();for(let i=0;i<16;i++)s.wait(false,undefined,false);expect(s.snapshot().activity).toBe('working');s.uncertain(true);expect(s.snapshot().outcome).toBe('unknown');expect(isExecutionState(s.snapshot())).toBe(true);const copy=s.snapshot();copy.activity='waiting';expect(s.snapshot().activity).toBe('idle');});
});
